### ISSUE TITLE
Erstellen von Formular und der Aufgabenliste 

### ISSUE THREAD

**Issue by Mitrovic-Milan** [Mitrovic-Milan/capstone-project-enhanced#1]
Value Proposition

Als Benutzer  
brauche ich ein Eingabefeld und eine Schaltfläche die meine aufgaben in eine Aufgabenliste als Text (Element) hinzufügt. 
Damit ich Aufgaben die ich habe nicht vergesse. 

## Description
<img width="550" alt="Todo 1" src="https://user-images.githubusercontent.com/104771076/180244216-4e40b14a-547d-4b1e-b8aa-8f10967e9518.png">

## Acceptance Criteria

- [x] Es gibt ein Eingabefeld mit dem kann ich Aufgaben in Textform hinzufügen
- [x] Das Eingabefeld ist requriert zum hinzufügen von Aufgaben, und darf max. 50 zeichen enthalten
- [x] mit dem Submit button wird der Text in das Listen (Element) eingefügt. 
- [x] Der Text erscheint in  Liste (Element).
- [x] Es gibt die Funktion des Scrollens falls man viele Aufgaben hat.

## Tasks

(for developers team)

- [x] Components erstellen Todo.js und TodoList.js
- [x] Erstellung des Formulars,(Überschrift, Eingabefeld, Schaltflächen (Submit)) 
- [x] die Schaltflächen werden in Storybook erstellt.
- [x] Das Listen (Element) wird erstelt als eine  <ul> Ungeordnetes Listen (Element).
- [ ] Die Scroll funktion wird implementiert.
- [ ]  maximal 50 Zeichen im input.
- [ ] styles, positionierung der Elemente. Das Eingabenfeld wird unten Links positioniert und die Schaltfläche wird daneben positioniert zudem wird die Schaltfläche mit Submit beschriftät.

**Comment by actyvystom** [comment]
Hi Milan,

this is a good start for a first user story!
Though a few thoughts to consider:
 
try to be more precise in your wording of tasks and acceptance criteria, e.g. you mention "Aufgabe" as a (text) value to be entered in the input field, and then it is added to the list of todos/tasks - I guess you should change the wording a little bit, as it is not the task itself, which will be displayed in the list, but a (list) element holding the text of the task and also a button which allows the user to delete the task/todo.

May sound a bit picky, but the clearer your descriptions, the easier to understand for you later and also for all other people reviewing or working with your user stories in the future :nerd_face:

**Comment by Mitrovic-Milan** [comment]
Thank you for looking at my user story and making an informed comment. 
I will take your comments into consideration and hope that you will like my new user story better.

**Comment by PReichetanz** [comment]
Hi Milan,

looks good to me!

Just three minor points:

- You don't need the second line "Offene Todos: 1" now, because you have not yet implemented the functionality to count the todos and display the current value.
- The "X"-Buttons are not mentioned anywhere - if they are meant to delete the todos, I think this should be another user story.
- So far, the user cannot make a todo item change the color from red to green, so your wireframe should only contain red items.

**Comment by Mitrovic-Milan** [comment]
Hi Paul,

thanks for looking at my user story and for the good comments. 
I have responded to your comments and hope they fit your idea

**Comment by PReichetanz** [comment]
Hi Milan,
the only thing left is the acceptance criteria "Das Input-Feld ist (not) required", depending on how you want to handle the input. If you have added this, I would say you are ready to go 🎉

**Comment by chris-yooo** [comment]
after changes from paul think this is a good story start :)
