### ISSUE TITLE
Delete Button 

### ISSUE THREAD

**Issue by Mitrovic-Milan** [Mitrovic-Milan/capstone-project-enhanced#2]
Value Proposition

Als Benutzer
brauche ich eine Delete Schaltfläche 
Damit ich in der Lage bin, erledigte Todos zu Löschen. 

## Description
<img width="356" alt="Delete " src="https://user-images.githubusercontent.com/104771076/180427182-eda71ddb-d256-4be7-a3f4-4d38be7f0951.png">

## Acceptance Criteria

- [x] Bei jedem neuen Todo erscheit ein Löschschaltfläche 
- [x] Auf der Löschschaltfläche befindet sich ein trash can Icon 
- [x] Wenn man die Löschfunktion drückt wird der Text aus dem Listen(Element) gelöscht. 

## Tasks

- [x] Erstellen der Löschfunktion
- [x]  Implementieren der Löschschaltfläche (inklusive Icon) in das Listen Element 
- [x] Schreiben einer Story in Storybook

**Comment by actyvystom** [comment]
Hi Milan, 
also a nice one, too :)

A few comments on this: 
- I doubt that a countdown is a good way to describe this scenario - imho I guess you will have a (mocked) data set of your todos, and each todo will probably have an attribute which indicates its status, e.g. 'done' or 'open', right?
  - so you could get the count information by traversing your todos and counting open ones and done todos  
 - You do not mention the delete functionality neither in your acceptance criteria nor does it show up in the wireframe - maybe better to create another user story for deleting todos
 - Think of adding tests and storybook components in your task list (the todo list element is also part of your first user story, maybe you better add them there)

**Comment by Mitrovic-Milan** [comment]
Hello Thomas, 

thank you for taking the time to read my second User Story. I have completely rewritten the user story and hope that it is okay for you.

**Comment by JessicaLoers** [comment]
**Hi @Mitrovic-Milan** ✌️
good work. 

_Just a few picky notes regarding the **Tasks** :_ 
I would recommend to change the order of your tasks and adjust them as followed: 

```
- Erstellen der Löschfunktion
- Implementieren der Löschschaltfläche (inklusive Icon) in das Listen Element 
- Schreiben einer Story in Storybook 
- Schreiben von Component Test 
```
The last one ( Component Test  ) is optional if you decide to not writing test. 😉

**Comment by Mitrovic-Milan** [comment]
Hello Jasica, 
Thank you very much for watching and for your good feedback. I will take your task list except for testing. I wanted to create my own user story for testing. What do you think about the idea? Thanks in advance.

**Comment by JessicaLoers** [comment]
**Hi @Mitrovic-Milan**
Yes, that's fine. You can write the test in a separate developer story afterwards. 🙂
