### ISSUE TITLE
Farben wechseln im Listenelement

### ISSUE THREAD

**Issue by Mitrovic-Milan** [Mitrovic-Milan/capstone-project-enhanced#5]
## Value proposition

Als benutzer,
benötige ich in meiner Liste einen Farblichen kontrast
damit ich weiss was ich bereits erledigt habe

## Description

![Farben wechsel ](https://user-images.githubusercontent.com/104771076/182555087-068af5da-9bd3-4a36-8eb2-7058304f3298.png)
 

## Acceptance criteria

- [x] Das Listenelement ist automatisch rot makiert. Das zeigt welche Todo noch offen sind.
- [x] Beim anclicken des Fertigen Todos ändert sich die Farbe von rot zu grün
- [x] Die noch nicht Fertigen Todos (rot makierten element) werden am oberen ende der Liste angezeigt  

## Complexity

Small 

## Tasks

- [x] neue branch erstellen 
- [x] Toggle Funktion inplementieren 
- [x] Fliter Funktion einbauen 
- [x] Style components

**Comment by chris-yooo** [comment]
Die US ist ansonsten US ok meiner meinung nach -> wie besprochen im Zoom 1 2 3 änderungen und dann GO

**Comment by Mitrovic-Milan** [comment]
Danke für dein feedback.

**Comment by ahohnsen** [comment]
Hey Milan, 

Ich würde dir empfehlen, deine Skizze etwas zu vergrößern, damit alles besser erkennbar ist :)
