### ISSUE TITLE
Datum und Uhrzeitstampel

### ISSUE THREAD

**Issue by Mitrovic-Milan** [Mitrovic-Milan/capstone-project-enhanced#8]
## Value proposition

Als Benuzer,
benötige ich in meiner Liste einen Zeitsampel und Datum Anzeige.
damit ich weiss, wielange ich für die Aufgabe brauche um in der Zukunft meine Aufgaben besser Planen kann.

## Description

<img width="404" alt="Time" src="https://user-images.githubusercontent.com/104771076/184318575-4fb963fa-7890-436a-bc78-9200dcd67713.png">

## Acceptance criteria

- [ ] Datum und Uhr anzeige um zu wissen wann hat man sich die Aufgabe gegeben und um zu Wissen wie lange man brauchte um die Aufgabe zu erledigen  

## Complexity

Small 

## Tasks

- [ ] Create branch
- [ ] erstelle einen neuen Ordner (util)
- [ ] erstelle eine neue Datei (CurrentData)
- [ ] Implementire die Funktion 
- [ ] Styles Components
